import { SaleReturnsService } from './sale-returns.service';
import type { AuthUser } from '@jewelry-erp/shared';
export declare class SaleReturnsController {
    private readonly saleReturnsService;
    constructor(saleReturnsService: SaleReturnsService);
    findAll(query: Record<string, unknown>): Promise<{
        data: ({
            customer: {
                id: string;
                name: string;
            } | null;
            saleInvoice: {
                number: string;
                id: string;
            };
            _count: {
                items: number;
            };
        } & {
            number: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            postedAt: Date | null;
            saleInvoiceId: string;
            returnDate: Date;
            refundAmount: import("@prisma/client/runtime/library").Decimal;
        })[];
        meta: {
            page: number;
            pageSize: number;
            total: number;
        };
    }>;
    findOne(id: string): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
    }>;
    create(body: unknown, user: AuthUser): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
    }>;
    post(id: string, body: unknown, user: AuthUser): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
    }>;
}
