import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
export declare class ProductsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(query: Record<string, unknown>): Promise<{
        data: {
            category: {
                id: string;
                deletedAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
                name: string;
            } | null;
            brand: {
                id: string;
                deletedAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
                name: string;
            } | null;
            stockBalance: {
                id: string;
                updatedAt: Date;
                onHandQty: Prisma.Decimal;
                onHandWeight: Prisma.Decimal;
                reservedQty: Prisma.Decimal;
                reservedWeight: Prisma.Decimal;
                damagedQty: Prisma.Decimal;
                damagedWeight: Prisma.Decimal;
                productId: string;
            } | null;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            description: string | null;
            grossWeight: Prisma.Decimal;
            netWeight: Prisma.Decimal;
            stoneWeight: Prisma.Decimal;
            makingCharges: Prisma.Decimal;
            stoneCharges: Prisma.Decimal;
            vatRate: Prisma.Decimal | null;
            purchasePrice: Prisma.Decimal;
            sellingPrice: Prisma.Decimal;
            minStockWeight: Prisma.Decimal;
            status: import("@prisma/client").$Enums.ProductStatus;
            barcode: string | null;
            sku: string;
            imagePath: string | null;
            categoryId: string | null;
            brandId: string | null;
            productType: import("@prisma/client").$Enums.ProductType;
            stockMode: import("@prisma/client").$Enums.StockMode;
            purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
            minStockQty: Prisma.Decimal;
        }[];
        meta: {
            page: number;
            pageSize: number;
            total: number;
        };
    }>;
    findOne(id: string): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: Prisma.Decimal;
            onHandWeight: Prisma.Decimal;
            reservedQty: Prisma.Decimal;
            reservedWeight: Prisma.Decimal;
            damagedQty: Prisma.Decimal;
            damagedWeight: Prisma.Decimal;
            productId: string;
        } | null;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: Prisma.Decimal;
        netWeight: Prisma.Decimal;
        stoneWeight: Prisma.Decimal;
        makingCharges: Prisma.Decimal;
        stoneCharges: Prisma.Decimal;
        vatRate: Prisma.Decimal | null;
        purchasePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        minStockWeight: Prisma.Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: Prisma.Decimal;
    }>;
    create(body: unknown, userId?: string): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: Prisma.Decimal;
            onHandWeight: Prisma.Decimal;
            reservedQty: Prisma.Decimal;
            reservedWeight: Prisma.Decimal;
            damagedQty: Prisma.Decimal;
            damagedWeight: Prisma.Decimal;
            productId: string;
        } | null;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: Prisma.Decimal;
        netWeight: Prisma.Decimal;
        stoneWeight: Prisma.Decimal;
        makingCharges: Prisma.Decimal;
        stoneCharges: Prisma.Decimal;
        vatRate: Prisma.Decimal | null;
        purchasePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        minStockWeight: Prisma.Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: Prisma.Decimal;
    }>;
    update(id: string, body: unknown, userId?: string): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: Prisma.Decimal;
            onHandWeight: Prisma.Decimal;
            reservedQty: Prisma.Decimal;
            reservedWeight: Prisma.Decimal;
            damagedQty: Prisma.Decimal;
            damagedWeight: Prisma.Decimal;
            productId: string;
        } | null;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: Prisma.Decimal;
        netWeight: Prisma.Decimal;
        stoneWeight: Prisma.Decimal;
        makingCharges: Prisma.Decimal;
        stoneCharges: Prisma.Decimal;
        vatRate: Prisma.Decimal | null;
        purchasePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        minStockWeight: Prisma.Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: Prisma.Decimal;
    }>;
    remove(id: string, userId?: string): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: Prisma.Decimal;
            onHandWeight: Prisma.Decimal;
            reservedQty: Prisma.Decimal;
            reservedWeight: Prisma.Decimal;
            damagedQty: Prisma.Decimal;
            damagedWeight: Prisma.Decimal;
            productId: string;
        } | null;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: Prisma.Decimal;
        netWeight: Prisma.Decimal;
        stoneWeight: Prisma.Decimal;
        makingCharges: Prisma.Decimal;
        stoneCharges: Prisma.Decimal;
        vatRate: Prisma.Decimal | null;
        purchasePrice: Prisma.Decimal;
        sellingPrice: Prisma.Decimal;
        minStockWeight: Prisma.Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: Prisma.Decimal;
    }>;
    private serializeProduct;
}
