import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { NumberSeriesService } from '../number-series/number-series.service';
import { InventoryService } from '../inventory/inventory.service';
import { AccountingService } from '../accounting/accounting.service';
export declare class SaleReturnsService {
    private readonly prisma;
    private readonly numberSeries;
    private readonly inventory;
    private readonly accounting;
    constructor(prisma: PrismaService, numberSeries: NumberSeriesService, inventory: InventoryService, accounting: AccountingService);
    findAll(query: Record<string, unknown>): Promise<{
        data: ({
            customer: {
                id: string;
                name: string;
            } | null;
            saleInvoice: {
                number: string;
                id: string;
            };
            _count: {
                items: number;
            };
        } & {
            number: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            total: Prisma.Decimal;
            taxable: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            postedAt: Date | null;
            saleInvoiceId: string;
            returnDate: Date;
            refundAmount: Prisma.Decimal;
        })[];
        meta: {
            page: number;
            pageSize: number;
            total: number;
        };
    }>;
    findOne(id: string): Promise<{
        items: {
            id: string;
            netWeight: Prisma.Decimal;
            vatRate: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            productId: string;
            quantity: Prisma.Decimal;
            lineNet: Prisma.Decimal;
            lineTotal: Prisma.Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: Prisma.Decimal;
            currentBalance: Prisma.Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: Prisma.Decimal;
            subtotal: Prisma.Decimal;
            discount: Prisma.Decimal;
            taxable: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            paid: Prisma.Decimal;
            balance: Prisma.Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: Prisma.Decimal;
        taxable: Prisma.Decimal;
        vatAmount: Prisma.Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: Prisma.Decimal;
    }>;
    createFromSale(body: unknown, userId?: string): Promise<{
        items: {
            id: string;
            netWeight: Prisma.Decimal;
            vatRate: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            productId: string;
            quantity: Prisma.Decimal;
            lineNet: Prisma.Decimal;
            lineTotal: Prisma.Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: Prisma.Decimal;
            currentBalance: Prisma.Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: Prisma.Decimal;
            subtotal: Prisma.Decimal;
            discount: Prisma.Decimal;
            taxable: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            paid: Prisma.Decimal;
            balance: Prisma.Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: Prisma.Decimal;
        taxable: Prisma.Decimal;
        vatAmount: Prisma.Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: Prisma.Decimal;
    }>;
    post(id: string, body: unknown, userId?: string): Promise<{
        items: {
            id: string;
            netWeight: Prisma.Decimal;
            vatRate: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            productId: string;
            quantity: Prisma.Decimal;
            lineNet: Prisma.Decimal;
            lineTotal: Prisma.Decimal;
            saleReturnId: string;
        }[];
        customer: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: Prisma.Decimal;
            currentBalance: Prisma.Decimal;
            civilId: string | null;
            notes: string | null;
        } | null;
        saleInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: Prisma.Decimal;
            subtotal: Prisma.Decimal;
            discount: Prisma.Decimal;
            taxable: Prisma.Decimal;
            vatAmount: Prisma.Decimal;
            paid: Prisma.Decimal;
            balance: Prisma.Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            customerId: string | null;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: Prisma.Decimal;
        taxable: Prisma.Decimal;
        vatAmount: Prisma.Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        customerId: string | null;
        postedAt: Date | null;
        saleInvoiceId: string;
        returnDate: Date;
        refundAmount: Prisma.Decimal;
    }>;
}
