import { PurchaseReturnsService } from './purchase-returns.service';
import type { AuthUser } from '@jewelry-erp/shared';
export declare class PurchaseReturnsController {
    private readonly purchaseReturnsService;
    constructor(purchaseReturnsService: PurchaseReturnsService);
    findAll(query: Record<string, unknown>): Promise<{
        data: ({
            supplier: {
                id: string;
                name: string;
            };
            purchaseInvoice: {
                number: string;
                id: string;
            };
        } & {
            number: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            postedAt: Date | null;
            supplierId: string;
            returnDate: Date;
            refundAmount: import("@prisma/client/runtime/library").Decimal;
            purchaseInvoiceId: string;
        })[];
        meta: {
            page: number;
            pageSize: number;
            total: number;
        };
    }>;
    findOne(id: string): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            purchaseReturnId: string;
        }[];
        supplier: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            tradeLicense: string | null;
        };
        purchaseInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
            supplierId: string;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        postedAt: Date | null;
        supplierId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
        purchaseInvoiceId: string;
    }>;
    create(body: unknown, user: AuthUser): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            purchaseReturnId: string;
        }[];
        supplier: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            tradeLicense: string | null;
        };
        purchaseInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
            supplierId: string;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        postedAt: Date | null;
        supplierId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
        purchaseInvoiceId: string;
    }>;
    post(id: string, body: unknown, user: AuthUser): Promise<{
        items: {
            id: string;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            productId: string;
            quantity: import("@prisma/client/runtime/library").Decimal;
            lineNet: import("@prisma/client/runtime/library").Decimal;
            lineTotal: import("@prisma/client/runtime/library").Decimal;
            purchaseReturnId: string;
        }[];
        supplier: {
            id: string;
            email: string | null;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            address: string | null;
            phone: string | null;
            openingBalance: import("@prisma/client/runtime/library").Decimal;
            currentBalance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            tradeLicense: string | null;
        };
        purchaseInvoice: {
            number: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            total: import("@prisma/client/runtime/library").Decimal;
            subtotal: import("@prisma/client/runtime/library").Decimal;
            discount: import("@prisma/client/runtime/library").Decimal;
            taxable: import("@prisma/client/runtime/library").Decimal;
            vatAmount: import("@prisma/client/runtime/library").Decimal;
            paid: import("@prisma/client/runtime/library").Decimal;
            balance: import("@prisma/client/runtime/library").Decimal;
            notes: string | null;
            status: import("@prisma/client").$Enums.DocumentStatus;
            invoiceDate: Date;
            postedAt: Date | null;
            voidedAt: Date | null;
            supplierId: string;
        };
        number: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        total: import("@prisma/client/runtime/library").Decimal;
        taxable: import("@prisma/client/runtime/library").Decimal;
        vatAmount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        status: import("@prisma/client").$Enums.DocumentStatus;
        postedAt: Date | null;
        supplierId: string;
        returnDate: Date;
        refundAmount: import("@prisma/client/runtime/library").Decimal;
        purchaseInvoiceId: string;
    }>;
}
