import { ProductsService } from './products.service';
import type { AuthUser } from '@jewelry-erp/shared';
export declare class ProductsController {
    private readonly productsService;
    constructor(productsService: ProductsService);
    findAll(query: Record<string, unknown>): Promise<{
        data: {
            category: {
                id: string;
                deletedAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
                name: string;
            } | null;
            brand: {
                id: string;
                deletedAt: Date | null;
                createdAt: Date;
                updatedAt: Date;
                name: string;
            } | null;
            stockBalance: {
                id: string;
                updatedAt: Date;
                onHandQty: import("@prisma/client/runtime/library").Decimal;
                onHandWeight: import("@prisma/client/runtime/library").Decimal;
                reservedQty: import("@prisma/client/runtime/library").Decimal;
                reservedWeight: import("@prisma/client/runtime/library").Decimal;
                damagedQty: import("@prisma/client/runtime/library").Decimal;
                damagedWeight: import("@prisma/client/runtime/library").Decimal;
                productId: string;
            } | null;
            onHandQty: string;
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            createdById: string | null;
            updatedById: string | null;
            name: string;
            description: string | null;
            grossWeight: import("@prisma/client/runtime/library").Decimal;
            netWeight: import("@prisma/client/runtime/library").Decimal;
            stoneWeight: import("@prisma/client/runtime/library").Decimal;
            makingCharges: import("@prisma/client/runtime/library").Decimal;
            stoneCharges: import("@prisma/client/runtime/library").Decimal;
            vatRate: import("@prisma/client/runtime/library").Decimal | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal;
            sellingPrice: import("@prisma/client/runtime/library").Decimal;
            minStockWeight: import("@prisma/client/runtime/library").Decimal;
            status: import("@prisma/client").$Enums.ProductStatus;
            barcode: string | null;
            sku: string;
            ownership: import("@prisma/client").$Enums.ProductOwnership;
            imagePath: string | null;
            categoryId: string | null;
            brandId: string | null;
            productType: import("@prisma/client").$Enums.ProductType;
            stockMode: import("@prisma/client").$Enums.StockMode;
            purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
            minStockQty: import("@prisma/client/runtime/library").Decimal;
        }[];
        meta: {
            page: number;
            pageSize: number;
            total: number;
        };
    }>;
    findOne(id: string): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: import("@prisma/client/runtime/library").Decimal;
            onHandWeight: import("@prisma/client/runtime/library").Decimal;
            reservedQty: import("@prisma/client/runtime/library").Decimal;
            reservedWeight: import("@prisma/client/runtime/library").Decimal;
            damagedQty: import("@prisma/client/runtime/library").Decimal;
            damagedWeight: import("@prisma/client/runtime/library").Decimal;
            productId: string;
        } | null;
        onHandQty: string;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: import("@prisma/client/runtime/library").Decimal;
        netWeight: import("@prisma/client/runtime/library").Decimal;
        stoneWeight: import("@prisma/client/runtime/library").Decimal;
        makingCharges: import("@prisma/client/runtime/library").Decimal;
        stoneCharges: import("@prisma/client/runtime/library").Decimal;
        vatRate: import("@prisma/client/runtime/library").Decimal | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal;
        sellingPrice: import("@prisma/client/runtime/library").Decimal;
        minStockWeight: import("@prisma/client/runtime/library").Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        ownership: import("@prisma/client").$Enums.ProductOwnership;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: import("@prisma/client/runtime/library").Decimal;
    }>;
    create(body: unknown, user: AuthUser): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: import("@prisma/client/runtime/library").Decimal;
            onHandWeight: import("@prisma/client/runtime/library").Decimal;
            reservedQty: import("@prisma/client/runtime/library").Decimal;
            reservedWeight: import("@prisma/client/runtime/library").Decimal;
            damagedQty: import("@prisma/client/runtime/library").Decimal;
            damagedWeight: import("@prisma/client/runtime/library").Decimal;
            productId: string;
        } | null;
        onHandQty: string;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: import("@prisma/client/runtime/library").Decimal;
        netWeight: import("@prisma/client/runtime/library").Decimal;
        stoneWeight: import("@prisma/client/runtime/library").Decimal;
        makingCharges: import("@prisma/client/runtime/library").Decimal;
        stoneCharges: import("@prisma/client/runtime/library").Decimal;
        vatRate: import("@prisma/client/runtime/library").Decimal | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal;
        sellingPrice: import("@prisma/client/runtime/library").Decimal;
        minStockWeight: import("@prisma/client/runtime/library").Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        ownership: import("@prisma/client").$Enums.ProductOwnership;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: import("@prisma/client/runtime/library").Decimal;
    }>;
    update(id: string, body: unknown, user: AuthUser): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: import("@prisma/client/runtime/library").Decimal;
            onHandWeight: import("@prisma/client/runtime/library").Decimal;
            reservedQty: import("@prisma/client/runtime/library").Decimal;
            reservedWeight: import("@prisma/client/runtime/library").Decimal;
            damagedQty: import("@prisma/client/runtime/library").Decimal;
            damagedWeight: import("@prisma/client/runtime/library").Decimal;
            productId: string;
        } | null;
        onHandQty: string;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: import("@prisma/client/runtime/library").Decimal;
        netWeight: import("@prisma/client/runtime/library").Decimal;
        stoneWeight: import("@prisma/client/runtime/library").Decimal;
        makingCharges: import("@prisma/client/runtime/library").Decimal;
        stoneCharges: import("@prisma/client/runtime/library").Decimal;
        vatRate: import("@prisma/client/runtime/library").Decimal | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal;
        sellingPrice: import("@prisma/client/runtime/library").Decimal;
        minStockWeight: import("@prisma/client/runtime/library").Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        ownership: import("@prisma/client").$Enums.ProductOwnership;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: import("@prisma/client/runtime/library").Decimal;
    }>;
    remove(id: string, user: AuthUser): Promise<{
        category: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        brand: {
            id: string;
            deletedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            name: string;
        } | null;
        stockBalance: {
            id: string;
            updatedAt: Date;
            onHandQty: import("@prisma/client/runtime/library").Decimal;
            onHandWeight: import("@prisma/client/runtime/library").Decimal;
            reservedQty: import("@prisma/client/runtime/library").Decimal;
            reservedWeight: import("@prisma/client/runtime/library").Decimal;
            damagedQty: import("@prisma/client/runtime/library").Decimal;
            damagedWeight: import("@prisma/client/runtime/library").Decimal;
            productId: string;
        } | null;
        onHandQty: string;
        id: string;
        deletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        createdById: string | null;
        updatedById: string | null;
        name: string;
        description: string | null;
        grossWeight: import("@prisma/client/runtime/library").Decimal;
        netWeight: import("@prisma/client/runtime/library").Decimal;
        stoneWeight: import("@prisma/client/runtime/library").Decimal;
        makingCharges: import("@prisma/client/runtime/library").Decimal;
        stoneCharges: import("@prisma/client/runtime/library").Decimal;
        vatRate: import("@prisma/client/runtime/library").Decimal | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal;
        sellingPrice: import("@prisma/client/runtime/library").Decimal;
        minStockWeight: import("@prisma/client/runtime/library").Decimal;
        status: import("@prisma/client").$Enums.ProductStatus;
        barcode: string | null;
        sku: string;
        ownership: import("@prisma/client").$Enums.ProductOwnership;
        imagePath: string | null;
        categoryId: string | null;
        brandId: string | null;
        productType: import("@prisma/client").$Enums.ProductType;
        stockMode: import("@prisma/client").$Enums.StockMode;
        purityKarat: import("@prisma/client").$Enums.GoldKarat | null;
        minStockQty: import("@prisma/client/runtime/library").Decimal;
    }>;
}
